/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/openshift/auth-config-operator/pkg/apis/auth/v1alpha1"
	scheme "github.com/openshift/auth-config-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterAuthenticationsGetter has a method to return a ClusterAuthenticationInterface.
// A group's client should implement this interface.
type ClusterAuthenticationsGetter interface {
	ClusterAuthentications(namespace string) ClusterAuthenticationInterface
}

// ClusterAuthenticationInterface has methods to work with ClusterAuthentication resources.
type ClusterAuthenticationInterface interface {
	Create(*v1alpha1.ClusterAuthentication) (*v1alpha1.ClusterAuthentication, error)
	Update(*v1alpha1.ClusterAuthentication) (*v1alpha1.ClusterAuthentication, error)
	UpdateStatus(*v1alpha1.ClusterAuthentication) (*v1alpha1.ClusterAuthentication, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterAuthentication, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterAuthenticationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterAuthentication, err error)
	ClusterAuthenticationExpansion
}

// clusterAuthentications implements ClusterAuthenticationInterface
type clusterAuthentications struct {
	client rest.Interface
	ns     string
}

// newClusterAuthentications returns a ClusterAuthentications
func newClusterAuthentications(c *AuthV1alpha1Client, namespace string) *clusterAuthentications {
	return &clusterAuthentications{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterAuthentication, and returns the corresponding clusterAuthentication object, and an error if there is any.
func (c *clusterAuthentications) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterAuthentication, err error) {
	result = &v1alpha1.ClusterAuthentication{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterauthentications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterAuthentications that match those selectors.
func (c *clusterAuthentications) List(opts v1.ListOptions) (result *v1alpha1.ClusterAuthenticationList, err error) {
	result = &v1alpha1.ClusterAuthenticationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterauthentications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterAuthentications.
func (c *clusterAuthentications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterauthentications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a clusterAuthentication and creates it.  Returns the server's representation of the clusterAuthentication, and an error, if there is any.
func (c *clusterAuthentications) Create(clusterAuthentication *v1alpha1.ClusterAuthentication) (result *v1alpha1.ClusterAuthentication, err error) {
	result = &v1alpha1.ClusterAuthentication{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterauthentications").
		Body(clusterAuthentication).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterAuthentication and updates it. Returns the server's representation of the clusterAuthentication, and an error, if there is any.
func (c *clusterAuthentications) Update(clusterAuthentication *v1alpha1.ClusterAuthentication) (result *v1alpha1.ClusterAuthentication, err error) {
	result = &v1alpha1.ClusterAuthentication{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterauthentications").
		Name(clusterAuthentication.Name).
		Body(clusterAuthentication).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterAuthentications) UpdateStatus(clusterAuthentication *v1alpha1.ClusterAuthentication) (result *v1alpha1.ClusterAuthentication, err error) {
	result = &v1alpha1.ClusterAuthentication{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterauthentications").
		Name(clusterAuthentication.Name).
		SubResource("status").
		Body(clusterAuthentication).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterAuthentication and deletes it. Returns an error if one occurs.
func (c *clusterAuthentications) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterauthentications").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterAuthentications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterauthentications").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterAuthentication.
func (c *clusterAuthentications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterAuthentication, err error) {
	result = &v1alpha1.ClusterAuthentication{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterauthentications").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
